builds:
  - dir: ecr-login/cli/docker-credential-ecr-login/
    binary: docker-credential-ecr-login
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/awslabs/amazon-ecr-credential-helper/ecr-login/version.Version={{.Version}}
      - -X github.com/awslabs/amazon-ecr-credential-helper/ecr-login/version.GitCommitSHA={{.Commit}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
